name: clean_code_with_retrofit
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  #network calls
  retrofit: ^4.0.1
  dio: ^5.2.1+1

  #dependancy injection
  get_it: ^7.6.0
  injectable: ^2.1.2

  #ui
  sizer: ^2.0.15
  responsive_framework: ^1.1.0
  google_fonts: ^5.0.0
  go_router: ^8.0.5

  #state management
  flutter_bloc: ^8.1.3
  bloc_concurrency: ^0.2.2
  stream_transform: ^2.1.0
  equatable: ^2.0.5

  #database
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  #utils  
  json_annotation: ^4.8.1
  logger: ^1.4.0
  sentry_flutter: ^7.7.0 
  dartz: ^0.10.1
  flutter_dotenv: ^5.1.0
  
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  retrofit_generator: ^7.0.1
  build_runner: ^2.4.5
  json_serializable: ^6.7.0
  hive_generator: ^2.0.0
 
flutter:

  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/svg/
    - assets/fonts/
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
